/*
 * Copyright (c) 2022 Eben Howard, Tommy Ettinger, and contributors
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package squidpony;

/**
 * Tags used by SquidLib when calling libgdx's logging system. In the
 * {@code util}-part nevertheless, in case you define a {@code util}-only
 * interface that is backed up libgdx's logging system.
 * 
 * <p>
 * Tags used are gathered here, so that one can quickly the tags that SquidLib
 * use. This can be useful when analyzing logs generated by SquidLib. They are
 * all prefixed by {@code "squid"} so that one can filter the (very large)
 * output of android by the prefix of each line.
 * </p>
 * 
 * @author smelC
 */
public class SquidTags {

	/**
	 * Use this tag when logging things about generating dungeons, monster, etc.
	 */
	public static final String GENERATION = "squid generation";

	/**
	 * Use this tag when logging things about the screen's layout.
	 */
	public static final String LAYOUT = "squid layout";

	/**
	 * Use this tag when logging things about screens or the context of gameplay changing.
	 */
	public static final String SCREEN = "squid screen";
}
