package squidpony;

/**
 * Tags used by SquidLib when calling libgdx's logging system. In the
 * {@code util}-part nevertheless, in case you define a {@code util}-only
 * interface that is backed up libgdx's logging system.
 * 
 * <p>
 * Tags used are gathered here, so that one can quickly the tags that SquidLib
 * use. This can be useful when analyzing logs generated by SquidLib.
 * </p>
 * 
 * @author smelC
 */
public class SquidTags {

	/**
	 * Use this tag when logging things about generating dungeons, monster, etc.
	 */
	public static final String GENERATION = "generation";

	/**
	 * Use this tag when logging things about the screen's layout.
	 */
	public static final String LAYOUT = "layout";

	/**
	 * Use this tag when logging things about AbstractSquidScreen or other
	 * screen-changing methods if your display has them..
	 */
	public static final String SCREEN = "screen";
}
